server:
  port: 9091
  # говорим серверу, чтобы при получении сигнала SIGTERM он более не принимал
  # новые запросы, но при этом выполнил те, что уже в работе в течение времени,
  # которое указано в настройке spring.lifecycle.timeout-per-shutdown-phase
  # по умолчанию 30 секунд
  # подробнее тут: https://habr.com/en/companies/maxilect/articles/666090/
  shutdown: graceful
  tomcat:
    # говорим Tomcat сколько времени ждать после открытия соединения до получения запроса.
    # Может быть полезно для защиты от DoS атак, когда клиент устанавливает соединение,
    # сервер выделяет поток для его обработки, но запрос не приходит.
    # Это же время Tomcat будет тратить на чтение тела запроса.
    connection-timeout: 3s
    # время, в течение которого Tomcat удерживает соединение открытым, ожидая новых запросов
    keep-alive-timeout: 20s
    # Tomcat использует пул потоков для обработки входящих соединений: одно соединение - один поток.
    # По умолчанию макимальное количество потоков в пуле - 200.
    threads:
      max: 200
      # минимальное количество потоков, которые будут созданы в пуле при старте сервера
      min-spare: 10
spring:
  application:
    name: menu-service
  lifecycle:
    timeout-per-shutdown-phase: 30s # время, в течение которого текущие запросы будут отрабатываться после получения сигнала SIGTERM
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:15432/menu_service_db
    hikari:
      # таймаут на получение соединения из пула соединений
      connection-timeout: 2000 # в миллисекундах
      # по умолчанию в приложении используется пул соединений с БД HikariCP.
      # его размер конфигурируется этой настройкой. Специалисты команды HikariCP рекомендуют
      # устанавливать количество соединений, исходя из формулы:
      # connections = ((core_count * 2) + effective_spindle_count)
      # где core_count - количество ядер процессора
      # effective_spindle_count - количество вращающихся дисков
      # Так как мы предполагаем, что будет использоваться SSD, вращающихся дисков не будет,
      # поэтому effective_spindle_count = 0
      # Мы также предполагаем, что количество ядер = 6, следовательно maximum-pool-size = 12
      # более подробно тут: https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing
      maximum-pool-size: 12
  jpa:
    open-in-view: false
    hibernate:
      # говорим hibernate, что необходимо провалидировать соответствие схемы БД и JPA модели
      ddl-auto: validate
    properties:
      hibernate:
        # говорим hibernate, чтобы выводимые в логи sql запросы были отфрматированы для удобства чтения
        format_sql: true
        # говорим hibernate показывать sql запросы в логах (для отладки и тестирования)
        show_sql: true
  # https://stackoverflow.com/a/69739888/548473
  config:
    import: ${configserver.import}
  cloud:
    config:
      import-check.enabled: false
      fail-fast: false

      request-connect-timeout: 5000
      request-read-timeout: 5000
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1

configserver:
  import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:9095}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

api:
  menu-create:
    summary: Создание блюда меню
    description: |
      Создает блюдо и сохраняет его в базе данных.
      Возвращает информацию о созданном блюде, включая его идентификатор.
  menu-delete:
    summary: Удаление блюда.
    description: Удаляет блюдо по идентификатору.
  menu-update:
    summary: Обновление блюда.
    description: Обновляет блюдо в соответствии с переданными в теле запроса параметрами.
  menu-get:
    summary: Получение блюда.
    description: Возвращает информацию о блюде по его идентификатору.
  menu-list-get:
    summary: Получение списка блюд.
    description: |
      Возвращает список блюд из указанной категории. Список может быть пустым, если в категории нет блюд.
      Доступные категории: breakfast, lunch, dinner, drinks, snacks, salads.
      Список отсортирован в соответствии с указанным параметром сортировки.
      Доступные параметры сортировки: 
      az - сортирует по названию в алфавитном порядке
      za - сортирует по названию в обратном порядке
      price_asc - сортирует по возрастанию цены
      price_desc - сортирует по убыванию цены
      date_asc - сортирует по дате создания меню в порядке возрастания
      date_desc - сортирует по дате создания меню в порядке убывания
  menu-info:
    summary: Получение информации о цене и доступности блюд.
    description: |
      Возвращает информацию о цене, названии и доступности блюда в ресторане. Если блюда нет в ресторане,
      его цена представлена null значением. Несмотря на то, что семантика запроса полностью
      соответствует HTTP GET запросу, используется именно POST, так как в теле запроса может
      быть передан длинный список названий блюд.
  response:
    createOk: Блюдо создано успешно
    createConflict: Блюдо не было создано, так как блюдо с таким названием уже существует в базе.
    createBadRequest: Блюдо не было создано, так как запрос содержит ошибки. Подробнее в сообщении об ошибке.
    deleteNoContent: Блюдо с идентификатором более не хранится в базе данных.
    updateOk: Блюдо успешно обновлено.
    notFound: Блюдо с таким идентификатором не найдено в базе данных.
    updateBadRequest: Блюдо не было обновлено, так как запрос содержит ошибки. Подробнее в сообщении об ошибке.
    getOk: Блюдо успешно найдено.
    getListOk: Список блюд по категории успешно сформирован.
    getListBadRequest: Список блюд невозможно сформировать, так как в запросе некорректные параметры.
    getMenuInfoBadRequest: Информацию о блюдах невозможно сформировать, так как в запросе некорректные параметры (список названий пуст).
    getMenuInfoOk: Информация о блюдах успешно сформирована.